---
- name: '(download) Create temporary download directory'
  win_file:
    path: '{{ telegraf_download_temp_directory }}'
    state: directory

- name: '(download) Download telegraf zip file' 
  win_get_url:
    force: no
    url: https://dl.influxdata.com/telegraf/releases/telegraf-{{ telegraf_version }}_windows_{{ telegraf_architecture }}.zip
    dest: '{{ telegraf_download_temp_directory }}/telegraf-{{ telegraf_version }}_windows_{{ telegraf_architecture }}.zip'

- name: '(download) Unzip telegraf'
  win_unzip:
    src: '{{ telegraf_download_temp_directory }}/telegraf-{{ telegraf_version }}_windows_{{ telegraf_architecture }}.zip'
    dest: '{{ telegraf_download_temp_directory }}'

- name: '(download) Copy telegraf executable file'
  win_copy:
    remote_src: yes
    src: '{{ telegraf_download_temp_directory }}/telegraf-{{ telegraf_version }}/telegraf.exe'
    dest: '{{ telegraf_executable }}'

- name: '(download) Remove temporary download directory'
  win_file:
    path: '{{ telegraf_download_temp_directory }}'
    state: absent